
name: GitHub Contribution Snake

# Controls when the workflow will run
on:
  schedule: # Run at 9 am (BRT) on the 1st of every month (12 PM UTC)
    - cron: '0 15 14 * *'
    #- cron: '0 12 1 * *'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate_snake_animation:
    name: Generate and Deploy Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gerar a animação da cobra
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: WMS66
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
